CREATE TABLE mcn_income_controlled_read_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    platform_code VARCHAR(32) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    request_body_hash VARCHAR(64) NOT NULL,
    input_cursor VARCHAR(1024),
    next_cursor VARCHAR(1024),
    delivery_hash VARCHAR(64),
    source_status VARCHAR(32) NOT NULL,
    http_status INT NOT NULL,
    latency_millis BIGINT NOT NULL,
    fact_count INT NOT NULL,
    new_count INT NOT NULL,
    duplicate_count INT NOT NULL,
    unmatched_count INT NOT NULL,
    comparison_status VARCHAR(32),
    retry_after_seconds INT,
    source_watermark LONGTEXT,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    INDEX idx_mcn_income_controlled_read_run_platform_time (platform_code, completed_at),
    UNIQUE KEY uk_mcn_income_controlled_read_run_run_id (run_id)
);
