CREATE TABLE mcn_income_reward_candidate_projection (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    source_system VARCHAR(32) NOT NULL,
    platform_code VARCHAR(32) NOT NULL,
    source_event_id VARCHAR(128) NOT NULL,
    raw_ledger_event_id BIGINT NOT NULL,
    source_revision VARCHAR(512) NOT NULL,
    business_date DATE NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    source_user_id BIGINT NULL,
    recipient_user_id BIGINT NULL,
    reward_level INT NOT NULL,
    invitation_version_no INT NULL,
    rule_id BIGINT NULL,
    rule_rate DECIMAL(8,6) NULL,
    base_amount DECIMAL(18,6) NOT NULL,
    candidate_amount DECIMAL(18,6) NULL,
    currency_code VARCHAR(16) NOT NULL,
    amount_unit VARCHAR(32) NOT NULL,
    candidate_status VARCHAR(64) NOT NULL,
    decision_reason VARCHAR(128) NOT NULL,
    projected_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mcn_income_reward_candidate UNIQUE (source_system, platform_code, source_event_id, reward_level),
    INDEX idx_mcn_income_reward_candidate_day (platform_code, business_date, candidate_status),
    INDEX idx_mcn_income_reward_candidate_recipient (recipient_user_id, candidate_status)
);

CREATE TABLE mcn_income_reward_candidate_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    platform_code VARCHAR(32) NOT NULL,
    business_date DATE NOT NULL,
    source_fact_count INT NOT NULL,
    source_ready_count INT NOT NULL,
    candidate_count INT NOT NULL,
    blocked_count INT NOT NULL,
    candidate_amount DECIMAL(18,6) NOT NULL,
    amount_unit VARCHAR(32) NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mcn_income_reward_candidate_run UNIQUE (run_id),
    INDEX idx_mcn_income_reward_candidate_run_day (platform_code, business_date, completed_at)
);
