CREATE TABLE mcn_income_reward_candidate_run_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    platform_code VARCHAR(32) NOT NULL,
    source_event_id VARCHAR(128) NOT NULL,
    raw_ledger_event_id BIGINT NOT NULL,
    source_revision VARCHAR(512) NOT NULL,
    business_date DATE NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    source_user_id BIGINT NULL,
    recipient_user_id BIGINT NULL,
    reward_level INT NOT NULL,
    invitation_version_no INT NULL,
    commission_policy_id BIGINT NULL,
    commission_policy_code VARCHAR(64) NULL,
    rule_rate DECIMAL(8,6) NULL,
    base_amount DECIMAL(18,6) NOT NULL,
    candidate_amount DECIMAL(18,6) NULL,
    currency_code VARCHAR(16) NOT NULL,
    amount_unit VARCHAR(32) NOT NULL,
    candidate_status VARCHAR(64) NOT NULL,
    decision_reason VARCHAR(128) NOT NULL,
    projected_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mcn_income_reward_candidate_run_item UNIQUE (run_id, source_event_id, reward_level),
    INDEX idx_mcn_income_reward_candidate_run_item_status (run_id, candidate_status),
    INDEX idx_mcn_income_reward_candidate_run_item_day (platform_code, business_date)
);
